apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  test: ${{ each val in values.allParameter | dump  echo val}}
  annotations:
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
